# florist/Taskfile (see https://taskfile.dev)

version: '3'
set: [pipefail]

tasks:

  pre-commit:
    cmds:
      - task: build
      - task: lint
      - task: check-coverage
      - cmd: go mod tidy

  build:example:
    desc: Build the example provisioner.
    cmds:
      - go build -o bin/example ./example

  build:dev:
    desc: Build the provisioner for the project
    cmds:
      - go build -o bin/dev ./florist/roles/dev
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/linux/dev ./florist/roles/dev

  build:
    desc: Test successful build.
    cmds:
      - go build ./...

  lint:
    cmds:
      - go vet ./...
      - staticcheck ./...

  test:
    desc: Run all the unit tests; makes sense only if invoking from the VM.
    cmds:
      - mkdir -p ./bin
      # - go clean -testcache
      - gotestsum -- -count=1 -coverprofile=./bin/coverage.out {{.pkg}}
    vars:
      pkg: '{{.pkg | default "./..."}}'

  test:all:vm:clean:
    desc: Run all the tests on a VM from a clean snapshot
    cmds:
      - task: _vm:restore
      - task: test:all:vm:dirty

  check-coverage:
    desc: 'Usage: task test check-coverage'
    vars:
      # This coverage is for non-destructive tests (host NOT disposable).
      COVERAGE_MAP:
        map:
          darwin: '26.6%'
          linux: '26.8%'
      # Can be set from command-line, see usage in .cirrus.yml
      COVERAGE: '{{default (index .COVERAGE_MAP OS) .COVERAGE}}'
    cmds:
      - cmd: |
          have=$(go tool cover -func ./bin/coverage.out | grep ^total: | awk '{print $3}')
          if [ $have != {{.COVERAGE}} ]; then
            echo "Coverage changed: have: $have; want: {{.COVERAGE}}"
            exit 1
          else
            echo "Coverage: $have"
          fi
        silent: true

  test:all:vm:dirty:
    desc: |
      Run all the tests on a VM on the current snapshot (thus dirty)
      (faster but inaccurate and flaky)
    cmds:
      - task: vm:set_date
      - ssh -F ssh.config.vagrant florist-vagrant "cd florist && sudo task test:all"

  vm:set_date:
    desc: Set the current date in the VM (expects the VM to be running).
    cmds:
      - ssh -F ssh.config.vagrant florist-vagrant sudo sntp --step 0.pool.ntp.org

  coverage:browser:
    desc: "Show code coverage in browser (usage: task test:<subtarget> browser)"
    cmds:
      - go tool cover -html=./bin/coverage.out

  clean:
    desc: Remove the build artifacts
    cmds:
      - rm -rf bin

  vm:init:
    desc: Create a VM from scratch, provision and take a snapshot. Use `vm:restore` to restore the snapshot to pristine state.
    cmds:
    - task: build:dev
    - vagrant destroy --force
    - vagrant up
    # Generate a SSH configuration file
    - vagrant ssh-config > ssh.config.vagrant
    # For some reason, vagrant adds "LogLevel FATAL" to the generated file.
    # We want the default logging level instead.
    - sed -i.bak 's/LogLevel FATAL//' ssh.config.vagrant
    - rm ssh.config.vagrant.bak
    # Mark this VM as a target for destructive tests.
    - ssh -F ssh.config.vagrant florist-vagrant sudo mkdir -p /opt/florist/disposable
    # Provision the VM with the "dev" bouquet.
    - ssh -F ssh.config.vagrant florist-vagrant sudo "./florist/bin/linux/dev install"
    # Install other deps. I am unsure this is the best approach...
    - ssh -F ssh.config.vagrant florist-vagrant "GOBIN=/usr/local/bin sudo --preserve-env=GOBIN task -d florist install:deps"
      # Take snapshot, name `pristine`
    - vagrant snapshot save pristine
    - vagrant halt

  vm:restore:
    desc: Restore the VM snapshot to pristine state and set the current date
    cmds:
      - task: _vm:restore
      - task: vm:set_date

  _vm:restore:
    cmds:
      - vagrant snapshot restore pristine

  install:deps:
    desc: Install tool dependencies.
    cmds:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install gotest.tools/gotestsum@latest

  pulumi:up:
    desc: Run pulumi up.
    cmds:
      - task: pulumi
        vars:
          CLI_ARGS: up {{if eq .preview "no"}}--skip-preview{{end}}
      - task: wait-for-conn
      - task: pulumi:mutagen:start
      - task: pulumi:init-vm

  pulumi:init-vm:
    cmds:
      - task: build:dev
      - rsync --quiet -P -a -t ./bin/linux/dev florist-hcloud:/opt/florist/
      - ssh florist-hcloud "mkdir -p /opt/florist/disposable"
      - ssh florist-hcloud "/opt/florist/dev --log-level=debug install"
      - ssh florist-hcloud "go install gotest.tools/gotestsum@latest"

  pulumi:refresh:
    desc: Run pulumi refresh.
    cmds:
      - task: pulumi
        vars:
          # To understand the fundamental --run-program, see
          # https://www.pulumi.com/blog/improved-refresh-destroy-experience/
          CLI_ARGS: refresh --run-program {{if eq .preview "no"}}--skip-preview{{end}}

  pulumi:down:
    desc: Run pulumi down.
    cmds:
      - task: pulumi:mutagen:stop
      - task: pulumi
        vars:
          # To understand the fundamental --run-program, see
          # https://www.pulumi.com/blog/improved-refresh-destroy-experience/
          CLI_ARGS: down --run-program {{if eq .preview "no"}}--skip-preview{{end}}

  pulumi:ssh:
    desc: Connect to the cloud VM.
    cmds:
      - ssh florist-hcloud fish {{.CLI_ARGS}}

  pulumi:test:
    desc: Run the tests on the cloud VM.
    cmds:
      - ssh florist-hcloud 'fish -c "cd florist && task test"'

  wait-for-conn:
    cmds:
      # Sometimes SSH is not ready yet when VM just created :-/
      -  go run ./cmd/wait-for-conn --verbose --max-wait=30s --address [{{.ADDR}}]:22
    vars:
      ADDR:
        sh: envchain florist pulumi -C pulumi stack output IPv6

  pulumi:all:
    desc: Bring up, run tests, tear down.
    cmds:
      - task: pulumi:down
        vars: {preview: no}
      - task: pulumi:up
        vars: {preview: no}
      - task: pulumi:test
      - task: pulumi:down
        vars: {preview: no}

  pulumi:
    desc: >
      Run 'pulumi' with secrets: task pulumi -- ...
    cmds:
      - envchain florist pulumi -C pulumi {{.CLI_ARGS}}
    vars:
      env: dev

  pulumi:mutagen:start:
    cmds:
      # One way from localhost to target.
      - |
        mutagen sync create \
        --name=florist-hcloud-src \
        --sync-mode=one-way-replica \
        --ignore='/.git/' \
        --ignore='/.jj/' \
        --ignore='/bin/' \
        ~/src/hw/florist florist-hcloud:~/florist
      # Bring back coverage data from target to localhost.
      - |
        mutagen sync create \
        --name=florist-hcloud-cover \
        --sync-mode=two-way-safe \
        --ignore='*' \
        --ignore='!cover*' \
        ~/src/hw/florist/bin florist-hcloud:~/florist/bin



  pulumi:mutagen:stop:
    cmds:
      - mutagen sync terminate florist-hcloud-src
      - mutagen sync terminate florist-hcloud-cover
      - mutagen sync list
    ignore_error: true

  hcloud:
    desc: >
      Run 'hcloud' with secrets: task hcloud -- ...
    cmds:
      - envchain florist hcloud {{.CLI_ARGS}}
