# https://taskfile.dev

version: '3'

vars:

tasks:
  build:
    desc: Build all
    cmds:
      - go build ./...
      - task: build:example

  build:example:
    desc: Build the example
    cmds:
      - go build -o bin/example-florist ./example
      - GOOS=linux go build -o bin/linux/example-florist ./example

  test:
    desc: Run all the tests
    cmds:
      - go test -count=1 -cover ./...

  clean:
    desc: Remove the build artifacts
    cmds:
      - rm -rf bin
