# https://taskfile.dev

version: '3'

vars:

tasks:
  build:
    desc: Build all
    cmds:
      - go build ./...
      - task: build:example

  build:example:
    desc: Build the example
    cmds:
      - go build -o bin/example-florist ./example
      - GOOS=linux go build -o bin/linux/example-florist ./example

  test:unit:
    desc: Run the unit tests
    cmds:
      - go test -count=1 -short -cover ./...

  test:vm:
    desc: Run the VM-based tests
    cmds:
      - go test -count=1 -run 'Test.*VM$' -cover ./...

  test:all:
    desc: Run all the tests (get all coverage)
    cmds:
      - go test -count=1 -cover ./...

  clean:
    desc: Remove the build artifacts
    cmds:
      - rm -rf bin
