# florist/Taskfile (see https://taskfile.dev)

version: '3'

vars:
  GOTESTSUM_VERSION: v1.8.2

tasks:
  build:example:install:
    desc: Build the example installer for the install step, so without secrets.
    cmds:
      - go build -o bin/example ./example

  build:example:configure:
    desc: Build the example installer for the configure step, so _with_ secrets.
      It is very important to remove the secrets also in case of failure, which we
      obtain with the Task "defer" keyword.
    cmds:
      - defer: rm -r ./example/embed/secrets
      - cmd: mkdir -p ./example/embed/secrets/flowers/daisy
      - cmd: mkdir -p ./example/embed/secrets/flowers/oleander
      - cmd: mkdir -p ./example/embed/secrets/nodes/controller/daisy
      - cmd: echo -n "the base secret value" > ./example/embed/secrets/flowers/daisy/secret
        silent: true
      - cmd: echo -n "the overridden secret value" > ./example/embed/secrets/nodes/controller/daisy/secret
        silent: true
      - cmd: echo -n "the custom value" > ./example/embed/secrets/flowers/daisy/custom
        silent: true
      - go build -o bin/example ./example

  build:installer:
    desc: Build the installer
    cmds:
      - go build -o bin/installer ./installer
      - GOOS=linux go build -o bin/linux/installer ./installer

  test:all:
    desc: Run all the unit tests; makes sense only if invoking from the VM.
    cmds:
      - gotestsum -- -count=1 -coverprofile=./bin/cover.out ./...

  test:all:vm:clean:
    desc: Run all the tests on a VM from a clean snapshot
    cmds:
      - task: _vm:restore
      - task: test:all:vm:dirty

  test:all:vm:dirty:
    desc: Run all the tests on a VM on the current snapshot (thus dirty) (faster but inaccurate and flaky)
    cmds:
      - task: vm:set_date
      - ssh -F ssh.config.vagrant florist-dev "cd florist && sudo task test:all"

  vm:set_date:
    desc: Set the current date in the VM (expects the VM to be running).
    cmds:
      - ssh -F ssh.config.vagrant florist-dev sudo sntp --step 0.pool.ntp.org

  browser:
    desc: "Show code coverage in browser (usage: task test:<subtarget> browser)"
    cmds:
      - go tool cover -html=./bin/cover.out

  clean:
    desc: Remove the build artifacts
    cmds:
      - rm -rf bin

  vm:init:
    desc: Create a VM from scratch, provision and take a snapshot. Use `vm:restore` to restore the snapshot to pristine state.
    cmds:
    - task: build:installer
    - vagrant destroy --force
    - vagrant up
    # Generate a SSH configuration file
    - vagrant ssh-config > ssh.config.vagrant
    # For some reasons, vagrant adds "LogLevel FATAL" to the generated file.
    # We want the default logging level instead.
    - sed -i "" 's/LogLevel FATAL//' ssh.config.vagrant
    # Mark this VM as a target for destructive tests.
    - ssh -F ssh.config.vagrant florist-dev sudo mkdir -p /opt/florist/disposable
    # Provision the dev flower 🌼
    - ssh -F ssh.config.vagrant florist-dev sudo "./florist/bin/linux/installer install dev"
    # Install other deps. I am unsure this is the best approach...
    - ssh -F ssh.config.vagrant florist-dev "GOBIN=/usr/local/bin sudo --preserve-env=GOBIN task -d florist install-deps"
      # Take snapshot, name `pristine`
    - vagrant snapshot save pristine
    - vagrant halt

  vm:restore:
    desc: Restore the VM snapshot to pristine state and set the current date
    cmds:
      - task: _vm:restore
      - task: vm:set_date

  _vm:restore:
    cmds:
      - vagrant snapshot restore pristine

  install-deps:
    desc: Install tool dependencies.
    cmds:
      - go install gotest.tools/gotestsum@{{.GOTESTSUM_VERSION}}
