# https://taskfile.dev

version: '3'

vars:
  GOLANGCI_VERSION: v1.43.0
  GOTESTSUM_VERSION: v1.7.0
  GOTESTSUM:
    sh: if which gotestsum > /dev/null; then echo gotestsum; fi
  GOTEST: "{{if .GOTESTSUM}}{{.GOTESTSUM}} --{{else}}go test{{end}}"
  #GOTEST: go test -v

tasks:
  build:
    desc: Build all
    cmds:
      - go build ./...
      - task: build:example

  build:example:
    desc: Build the example
    cmds:
      - go build -o bin/example-florist ./example
      - GOOS=linux go build -o bin/linux/example-florist ./example

  test:unit:
    desc: Run the unit tests on the host
    cmds:
      - '{{.GOTEST}} -count=1 -short -coverprofile=coverage.out ./...'

  test:vm:
    desc: Run the VM-based tests
    cmds:
      - go test -count=1 -run 'Test.*VM$' -cover ./...

  test:all:
    desc: Run all the tests (get all coverage)
    cmds:
      - go test -count=1 -cover ./...

  clean:
    desc: Remove the build artifacts
    cmds:
      - rm -rf bin
