# https://taskfile.dev

version: '3'

vars:

tasks:
  build:
    desc: Build all packages
    cmds:
      - go build ./...

  test:
    desc: Run the tests
    cmds:
      - set -o pipefail && go test -count=1 -cover ./... -json | tparse -all

  deps:
    desc: Install dependencies
    cmds:
      - go install github.com/mfridman/tparse@latest
